#!/bin/sh

cd /karchan/mud/sql   

. ./mysql_constants

${MYSQL_BIN} -v -v -v -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} >/karchan/mud/sql/scripts/dbstatus.txt <<END_OF_DATA

check table CHA, CON, DEX, INTL, STR, WIS, ability_scores, action, answers,
attributes, bantable, bogus_itemtable, bottable, characterinfo, claimed,
commands, depalias, events, family, familyvalues, guilds, help, items,
itemtable, logonmessage, mailtable, methods, negativeitem, objects, olditem,
oldmail, olduser, positiveitem, private_info, respawningitemtable, rooms,
sillynamestable, skills, skilltable, tmp_itemtable, tmp_mailtable,
tmp_usertable, treasure, unbantable, usertable;

END_OF_DATA

cat /karchan/mud/sql/scripts/dbstatus.txt | /bin/mail maarten_l@yahoo.com -s "Database Status report"

