import { AdminObject } from '../admin/admin-object.model';

export enum Sex { Male = 'male', Female = 'female', Other = 'other' }

export class MudCharacter implements AdminObject<string> {
    name: string | null = null;
    address: string | null = null;
    image: string | null = null;
    title: string | null = null;
    realname: string | null = null;
    email: string | null = null;
    race: string | null = null;
    sex: Sex | null = null;
    age: string | null = null;
    height: string | null = null;
    width: string | null = null;
    complexion: string | null = null;
    eyes: string | null = null;
    face: string | null = null;
    hair: string | null = null;
    beard: string | null = null;
    arm: string | null = null;
    leg: string | null = null;
    copper: number | null = null;
    room: number | null = null;
    lok: string | null = null;
    whimpy: number | null = null;
    experience: number | null = null;
    fightingwho: string | null = null;
    sleep: number | null = null;
    punishment: number | null = null;
    fightable: number | null = null;
    vitals: number | null = null;
    fysically: number | null = null;
    mentally: number | null = null;
    drinkstats: number | null = null;
    eatstats: number | null = null;
    active: boolean | null = null;
    lastlogin: Date | null = null;
    birth: Date | null = null;
    god: boolean | null = null;
    guild: string | null = null;
    strength: number | null = null;
    intelligence: number | null = null;
    dexterity: number | null = null;
    constitution: number | null = null;
    wisdom: number | null = null;
    practises: number | null = null;
    training: number | null = null;
    bandage: number | null = null;
    alignment: number | null = null;
    manastats: number | null = null;
    movementstats: number | null = null;
    maxmana: number | null = null;
    maxmove: number | null = null;
    maxvital: number | null = null;
    cgiServerSoftware: string | null = null;
    cgiServerName: string | null = null;
    cgiGatewayInterface: string | null = null;
    cgiServerProtocol: string | null = null;
    cgiServerPort: string | null = null;
    cgiRequestMethod: string | null = null;
    cgiPathInfo: string | null = null;
    cgiPathTranslated: string | null = null;
    cgiScriptName: string | null = null;
    cgiRemoteHost: string | null = null;
    cgiRemoteAddr: string | null = null;
    cgiAuthType: string | null = null;
    cgiRemoteUser: string | null = null;
    cgiRemoteIdent: string | null = null;
    cgiContentType: string | null = null;
    cgiAccept: string | null = null;
    cgiUserAgent: string | null = null;
    jumpmana: number | null = null;
    jumpmove: number | null = null;
    jumpvital: number | null = null;
    owner: string | null = null;
    creation: Date | null = null;
    notes: string | null = null;
    currentstate: string | null = null;
    lastcommand: Date | null = null;
    wieldleft: number | null = null;
    wieldright: number | null = null;
    wieldboth: number | null = null;
    wearhead: number | null = null;
    wearneck: number | null = null;
    weartorso: number | null = null;
    weararms: number | null = null;
    wearleftwrist: number | null = null;
    wearrightwrist: number | null = null;
    wearleftfinger: number | null = null;
    wearrightfinger: number | null = null;
    wearfeet: number | null = null;
    wearhands: number | null = null;
    wearfloatingnearby: number | null = null;
    wearwaist: number | null = null;
    wearlegs: number | null = null;
    weareyes: number | null = null;
    wearears: number | null = null;
    wearaboutbody: number | null = null;
    guildlevel: number | null = null;
    timeout: Date | null = null;
    visible: boolean | null = null;
    rrribbits: number | null = null;
    heehaws: number | null = null;
    ooc: boolean | null = null;
    newpassword: string | null = null;

    constructor(object?: any) {
        if (object === undefined) {
            return;
        }
        this.name = object.name;
        this.address = object.address;
        this.image = object.image;
        this.title = object.title;
        this.realname = object.realname;
        this.email = object.email;
        this.race = object.race;
        this.sex = object.sex;
        this.age = object.age;
        this.height = object.height;
        this.width = object.width;
        this.complexion = object.complexion;
        this.eyes = object.eyes;
        this.face = object.face;
        this.hair = object.hair;
        this.beard = object.beard;
        this.arm = object.arm;
        this.leg = object.leg;
        this.copper = object.copper;
        this.room = object.room;
        this.lok = object.lok;
        this.whimpy = object.whimpy;
        this.experience = object.experience;
        this.fightingwho = object.fightingwho;
        this.sleep = object.sleep;
        this.punishment = object.punishment;
        this.fightable = object.fightable;
        this.vitals = object.vitals;
        this.fysically = object.fysically;
        this.mentally = object.mentally;
        this.drinkstats = object.drinkstats;
        this.eatstats = object.eatstats;
        this.active = object.active;
        this.lastlogin = object.lastlogin;
        this.birth = object.birth;
        this.god = object.god;
        this.guild = object.guild;
        this.strength = object.strength;
        this.intelligence = object.intelligence;
        this.dexterity = object.dexterity;
        this.constitution = object.constitution;
        this.wisdom = object.wisdom;
        this.practises = object.practises;
        this.training = object.training;
        this.bandage = object.bandage;
        this.alignment = object.alignment;
        this.manastats = object.manastats;
        this.movementstats = object.movementstats;
        this.maxmana = object.maxmana;
        this.maxmove = object.maxmove;
        this.maxvital = object.maxvital;
        this.cgiServerSoftware = object.cgiServerSoftware;
        this.cgiServerName = object.cgiServerName;
        this.cgiGatewayInterface = object.cgiGatewayInterface;
        this.cgiServerProtocol = object.cgiServerProtocol;
        this.cgiServerPort = object.cgiServerPort;
        this.cgiRequestMethod = object.cgiRequestMethod;
        this.cgiPathInfo = object.cgiPathInfo;
        this.cgiPathTranslated = object.cgiPathTranslated;
        this.cgiScriptName = object.cgiScriptName;
        this.cgiRemoteHost = object.cgiRemoteHost;
        this.cgiRemoteAddr = object.cgiRemoteAddr;
        this.cgiAuthType = object.cgiAuthType;
        this.cgiRemoteUser = object.cgiRemoteUser;
        this.cgiRemoteIdent = object.cgiRemoteIdent;
        this.cgiContentType = object.cgiContentType;
        this.cgiAccept = object.cgiAccept;
        this.cgiUserAgent = object.cgiUserAgent;
        this.jumpmana = object.jumpmana;
        this.jumpmove = object.jumpmove;
        this.jumpvital = object.jumpvital;
        this.owner = object.owner;
        this.creation = object.creation;
        this.notes = object.notes;
        this.currentstate = object.currentstate;
        this.lastcommand = object.lastcommand;
        this.wieldleft = object.wieldleft;
        this.wieldright = object.wieldright;
        this.wieldboth = object.wieldboth;
        this.wearhead = object.wearhead;
        this.wearneck = object.wearneck;
        this.weartorso = object.weartorso;
        this.weararms = object.weararms;
        this.wearleftwrist = object.wearleftwrist;
        this.wearrightwrist = object.wearrightwrist;
        this.wearleftfinger = object.wearleftfinger;
        this.wearrightfinger = object.wearrightfinger;
        this.wearfeet = object.wearfeet;
        this.wearhands = object.wearhands;
        this.wearfloatingnearby = object.wearfloatingnearby;
        this.wearwaist = object.wearwaist;
        this.wearlegs = object.wearlegs;
        this.weareyes = object.weareyes;
        this.wearears = object.wearears;
        this.wearaboutbody = object.wearaboutbody;
        this.guildlevel = object.guildlevel;
        this.timeout = object.timeout;
        this.visible = object.visible;
        this.rrribbits = object.rrribbits;
        this.heehaws = object.heehaws;
        this.ooc = object.ooc;
        this.newpassword = object.newpassword;

    }

    getIdentifier(): string | null {
        return this.name;
    }

    setIdentifier(name: string): void {
        this.name = name;
    }

    getType(): string {
        return 'Character';
    }

}