import { AdminObject } from '../admin/admin-object.model';

export enum Sex { Male = 'male', Female = 'female', Other = 'other' }

export class MudCharacter implements AdminObject<string> {
    name: string;
    address: string;
    image: string;
    title: string;
    realname: string;
    email: string;
    race: string;
    sex: Sex;
    age: string;
    height: string;
    width: string;
    complexion: string;
    eyes: string;
    face: string;
    hair: string;
    beard: string;
    arm: string;
    leg: string;
    copper: number;
    room: number;
    lok: string;
    whimpy: number;
    experience: number;
    fightingwho: string;
    sleep: number;
    punishment: number;
    fightable: number;
    vitals: number;
    fysically: number;
    mentally: number;
    drinkstats: number;
    eatstats: number;
    active: boolean;
    lastlogin: Date;
    birth: Date;
    god: boolean;
    guild: string;
    strength: number;
    intelligence: number;
    dexterity: number;
    constitution: number;
    wisdom: number;
    practises: number;
    training: number;
    bandage: number;
    alignment: number;
    manastats: number;
    movementstats: number;
    maxmana: number;
    maxmove: number;
    maxvital: number;
    cgiServerSoftware: string;
    cgiServerName: string;
    cgiGatewayInterface: string;
    cgiServerProtocol: string;
    cgiServerPort: string;
    cgiRequestMethod: string;
    cgiPathInfo: string;
    cgiPathTranslated: string;
    cgiScriptName: string;
    cgiRemoteHost: string;
    cgiRemoteAddr: string;
    cgiAuthType: string;
    cgiRemoteUser: string;
    cgiRemoteIdent: string;
    cgiContentType: string;
    cgiAccept: string;
    cgiUserAgent: string;
    jumpmana: number;
    jumpmove: number;
    jumpvital: number;
    owner: string;
    creation: Date;
    notes: string;
    currentstate: string;
    lastcommand: Date;
    wieldleft: number;
    wieldright: number;
    wieldboth: number;
    wearhead: number;
    wearneck: number;
    weartorso: number;
    weararms: number;
    wearleftwrist: number;
    wearrightwrist: number;
    wearleftfinger: number;
    wearrightfinger: number;
    wearfeet: number;
    wearhands: number;
    wearfloatingnearby: number;
    wearwaist: number;
    wearlegs: number;
    weareyes: number;
    wearears: number;
    wearaboutbody: number;
    guildlevel: number;
    timeout: Date;
    visible: boolean;
    rrribbits: number;
    heehaws: number;
    ooc: boolean;
    newpassword: string;

    constructor(object?: any) {
        if (object === undefined) {
            return;
        }
        this.name = object.name;
        this.address = object.address;
        this.image = object.image;
        this.title = object.title;
        this.realname = object.realname;
        this.email = object.email;
        this.race = object.race;
        this.sex = object.sex;
        this.age = object.age;
        this.height = object.height;
        this.width = object.width;
        this.complexion = object.complexion;
        this.eyes = object.eyes;
        this.face = object.face;
        this.hair = object.hair;
        this.beard = object.beard;
        this.arm = object.arm;
        this.leg = object.leg;
        this.copper = object.copper;
        this.room = object.room;
        this.lok = object.lok;
        this.whimpy = object.whimpy;
        this.experience = object.experience;
        this.fightingwho = object.fightingwho;
        this.sleep = object.sleep;
        this.punishment = object.punishment;
        this.fightable = object.fightable;
        this.vitals = object.vitals;
        this.fysically = object.fysically;
        this.mentally = object.mentally;
        this.drinkstats = object.drinkstats;
        this.eatstats = object.eatstats;
        this.active = object.active;
        this.lastlogin = object.lastlogin;
        this.birth = object.birth;
        this.god = object.god;
        this.guild = object.guild;
        this.strength = object.strength;
        this.intelligence = object.intelligence;
        this.dexterity = object.dexterity;
        this.constitution = object.constitution;
        this.wisdom = object.wisdom;
        this.practises = object.practises;
        this.training = object.training;
        this.bandage = object.bandage;
        this.alignment = object.alignment;
        this.manastats = object.manastats;
        this.movementstats = object.movementstats;
        this.maxmana = object.maxmana;
        this.maxmove = object.maxmove;
        this.maxvital = object.maxvital;
        this.cgiServerSoftware = object.cgiServerSoftware;
        this.cgiServerName = object.cgiServerName;
        this.cgiGatewayInterface = object.cgiGatewayInterface;
        this.cgiServerProtocol = object.cgiServerProtocol;
        this.cgiServerPort = object.cgiServerPort;
        this.cgiRequestMethod = object.cgiRequestMethod;
        this.cgiPathInfo = object.cgiPathInfo;
        this.cgiPathTranslated = object.cgiPathTranslated;
        this.cgiScriptName = object.cgiScriptName;
        this.cgiRemoteHost = object.cgiRemoteHost;
        this.cgiRemoteAddr = object.cgiRemoteAddr;
        this.cgiAuthType = object.cgiAuthType;
        this.cgiRemoteUser = object.cgiRemoteUser;
        this.cgiRemoteIdent = object.cgiRemoteIdent;
        this.cgiContentType = object.cgiContentType;
        this.cgiAccept = object.cgiAccept;
        this.cgiUserAgent = object.cgiUserAgent;
        this.jumpmana = object.jumpmana;
        this.jumpmove = object.jumpmove;
        this.jumpvital = object.jumpvital;
        this.owner = object.owner;
        this.creation = object.creation;
        this.notes = object.notes;
        this.currentstate = object.currentstate;
        this.lastcommand = object.lastcommand;
        this.wieldleft = object.wieldleft;
        this.wieldright = object.wieldright;
        this.wieldboth = object.wieldboth;
        this.wearhead = object.wearhead;
        this.wearneck = object.wearneck;
        this.weartorso = object.weartorso;
        this.weararms = object.weararms;
        this.wearleftwrist = object.wearleftwrist;
        this.wearrightwrist = object.wearrightwrist;
        this.wearleftfinger = object.wearleftfinger;
        this.wearrightfinger = object.wearrightfinger;
        this.wearfeet = object.wearfeet;
        this.wearhands = object.wearhands;
        this.wearfloatingnearby = object.wearfloatingnearby;
        this.wearwaist = object.wearwaist;
        this.wearlegs = object.wearlegs;
        this.weareyes = object.weareyes;
        this.wearears = object.wearears;
        this.wearaboutbody = object.wearaboutbody;
        this.guildlevel = object.guildlevel;
        this.timeout = object.timeout;
        this.visible = object.visible;
        this.rrribbits = object.rrribbits;
        this.heehaws = object.heehaws;
        this.ooc = object.ooc;
        this.newpassword = object.newpassword;

    }

    getIdentifier(): string {
        return this.name;
    }

    setIdentifier(name: string): void {
        this.name = name;
    }

    getType(): string {
        return 'Character';
    }

}