#!groovy
pipeline {
    agent any
    tools { 
        maven 'Maven 3.3.9' 
        jdk 'jdk8' 
    }
    stages {
        stage('init') {
            steps {
                // jenkins-${JOB_NAME}-${BUILD_NUMBER}
                // for example jenkins-karchan-123sh '''
                echo "Build " + env.BUILD_TAG
                echo "Workspace " + env.WORKSPACE
                sh 'echo cp /home/glassfish/glassfish4/glassfish/domains/domain1/autodeploy/karchanscripts-1.0-SNAPSHOT.war /home/glassfish/karchanscripts-1.0-SNAPSHOT.war'
            }
        }
        stage('deploy') {
            steps {
                dir('karchanscripts') {
                    sh 'mvn verify' 
                }
            }
        }
    }
    post {
        success { 
            echo 'Deploying to glassfish...'
            sh 'cp karchanscripts/target/karchanscripts-1.0-SNAPSHOT.war /home/glassfish/glassfish4/glassfish/domains/domain1/autodeploy/'
        }
    }
}