#!groovy
pipeline {
    agent any
    tools { 
        maven 'Maven 3.3.9' 
        jdk 'jdk8' 
    }
    stages {
        stage('checkout') {
            steps {
                // jenkins-${JOB_NAME}-${BUILD_NUMBER}
                // for example jenkins-karchan-123sh '''
                echo "Build " + env.BUILD_TAG
                echo "Workspace " + env.WORKSPACE
                sh 'echo "<p>Suddenly Karn walks by carrying a toolbox and hammer and muttering to himself.</p>" | tee -a /home/glassfish/temp/*'
                sh 'cp /home/glassfish/glassfish4/glassfish/domains/domain1/autodeploy/karchangame.war /home/glassfish/backup/karchangame.war.backup'
            }
        }
        stage('build') {
            steps {
                dir('karchangame') {
                    sh 'mvn compile' 
                }
            }
        }
        stage('test') {
            steps {
                dir('karchangame') {
                    sh 'mvn test' 
                }
            }
            post {
                success {
                    junit 'karchangame/target/surefire-reports/**/*.xml' 
                }
            }
        } 
        stage('deploy') {
            steps {
                dir('karchangame') {
                    sh 'mvn verify' 
                }
            }
        }
        stage('docs') {
            steps {
                echo "Started generating javadoc"
                dir('karchangame') {
                    sh 'mvn javadoc:javadoc com.github.jeluard:plantuml-maven-plugin:generate'
                    sh 'cp -r target/site/apidocs/* ../karchandocs/src/main/webapp/'
                }
                dir('karchandocs') {
                    sh 'mvn verify'
                }
            }
        }
    }
    post {
        success { 
            echo 'Deploying to glassfish...'
            sh 'cp karchangame/target/karchangame-1.0-SNAPSHOT.war /home/glassfish/glassfish4/glassfish/domains/domain1/autodeploy/karchangame.war'
            sh 'cp karchandocs/target/karchandocs-1.0-SNAPSHOT.war /home/glassfish/glassfish4/glassfish/domains/domain1/autodeploy'
            sh 'rm /home/glassfish/temp/*'
        }
        failure {
            sh 'echo "<p>You suddenly hear the sound of someone hitting his own thumb, and cursing.</p>" | tee -a /home/glassfish/temp/*'
        }
    }
}
