#!groovy
pipeline {
    agent any
    tools { 
        maven 'Maven 3.3.9' 
        jdk 'jdk8' 
    }
    stages {
        stage('checkout') {
            steps {
                // jenkins-${JOB_NAME}-${BUILD_NUMBER}
                // for example jenkins-karchan-123sh '''
                echo "Build " + env.BUILD_TAG
                echo "Workspace " + env.WORKSPACE
                sh 'cp /home/glassfish/glassfish4/glassfish/domains/domain1/autodeploy/karchangame.war /home/glassfish/karchangame.war.backup'
            }
        }
        stage('build') {
            steps {
                dir('karchangame') {
                    sh 'mvn compile' 
                }
            }
        }
        stage('test') {
            steps {
                dir('karchangame') {
                    sh 'mvn test' 
                }
            }
            post {
                success {
                    junit 'karchangame/target/surefire-reports/**/*.xml' 
                }
            }
        } 
        stage('deploy') {
            steps {
                dir('karchangame') {
                    sh 'mvn verify' 
                }
            }
        }
    }
    post {
        success { 
            echo 'Deploying to glassfish...'
            sh 'cp karchangame/target/karchangame-1.0-SNAPSHOT.war /home/glassfish/glassfish4/glassfish/domains/domain1/autodeploy/karchangame.war'
        }
    }
}
