export const environment = {
  production: true,
  mock: false,
  ADMINISTRATORS_URL: '/karchangame/resources/administration/administrators',
  BLOGS_URL: '/karchangame/resources/administration/blogs',
  TEMPLATES_URL: '/karchangame/resources/administration/templates',
  SYSTEMLOG_URL: '/karchangame/resources/administration/systemlog',
  ROOMS_URL: '/karchangame/resources/administration/rooms',
  METHODS_URL: '/karchangame/resources/administration/methods',
  COMMANDS_URL: '/karchangame/resources/administration/commands',
  AREAS_URL: '/karchangame/resources/administration/areas',
  ITEMS_URL: '/karchangame/resources/administration/items',
  BAN_URL: '/karchangame/resources/administration/ban',
  MANPAGES_URL: '/karchangame/resources/administration/manpages',
  EVENTS_URL: '/karchangame/resources/administration/events',
  WORLDATTRIBUTES_URL: '/karchangame/resources/administration/worldattributes',
  CHARACTERS_URL: '/karchangame/resources/administration/characters',
  ATTRIBUTES_URL: '/karchangame/resources/administration/attributes',
};
