#!/bin/sh

cd /karchan/mud/sql/crontab

. ./../mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# Everyone who hasn't logged on for at least 90 days gets backupped and then
# erased.
#
select name, to_days(now())-to_days(lastlogin) from usertable where
to_days(now())-to_days(lastlogin)>90;

insert into olduser select * from usertable where
to_days(now())-to_days(lastlogin)>90;

delete from usertable where
to_days(now())-to_days(lastlogin)>90;

END_OF_DATA

