#!/bin/sh

cd /karchan/mud/sql/crontab

. ./../mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# Dumping data for table 'action'
#

# reset stones
update items set description='<H1>The Stones</H1><HR>
You look at the stones. They are solid and very big and they are
blocking your entrance to the north completely. What you should do is take a
heavy pick and demolish them, so that travelers may continue their trade.<P>
', adject1='big', adject2='heavy', adject3='hard' where id=-16;

update items set description='<H1>The Stones</H1><HR>
You look at the stones. They are solid and very big and they are
blocking your entrance to the south completely. What you should do is take a
heavy pick and demolish them, so that travelers may continue their trade.<P>
', adject1='big', adject2='heavy', adject3='hard' where id=-40;

update rooms set contents='<H1>The Road</H1> <Center><IMG
ALT=\"Mountain\"
SRC=\"http://www.karchan.org/images/jpeg/berg.jpg\"></Center><BR>
<IMG SRC=\"http://www.karchan.org/images/gif/letters/y.gif\"
ALIGN=left>ou
are standing on a road with leads North and South. Towards the south however
the road is blocked by heavy stones which make it impossible to cross.
Towards the north the road is tolerably well and would make travelling an
easy matter. To the west a forest stretches out. It is impossible to go to
the east due to the large mountains that are that way. You seem to be
trapped inside a valley, with mountains all around and the only way of
escape in to the wide world blocked. <P>', south=0 where id=4;

update rooms set contents='
<H1>The Other Side</H1> <Center><IMG ALT=\"Mountain\"
SRC=\"http://www.karchan.org/images/jpeg/berg.jpg\"></Center><BR>
You appear to be on the other side of a big range of mountains, which make
out a lonely valley. This appears to be a whole range of mountains, shutting
the people out from the outside world. To the north a lot of very extremely
big stones can be seen. That way is efficiently blocked off. The only way is
back to the south.<P>
', north=0 where id=23;

#reset cupboard door
update items set description='
<H1><IMG SRC=\"http://www.karchan.org/images/gif/herberg3.gif\">The Cupboard</H1><HR>
You look at the cupboard. It is very old and wormeaten. With one
knock you could probably knock it down, but I doubt if the barman would
appreciate this much. It hasn\'t got a lock so you could open it. I doubt if
the barman would mind.<P>', adject1='comparatively', adject2='big',
name='cupboard' where id=-32;

update rooms set contents='
<IMG SRC=\"http://www.karchan.org/images/gif/herberg1.gif\"
ALIGN=CENTER><H1>The Taverne &quot;The Twisted Dwarf&quot;</H1> <IMG
SRC=\"http://www.karchan.org/images/gif/letters/y.gif\" ALIGN=left>ou are
now in the Inn &quot;The Twisted Dwarf&quot; . It is dark, as always in
these places. The windows are of a dark blue color, which doesn\'t allow
any light to enter the room. A lot of woodwork, wooden tables, chairs and a
rather large bar on the right of you is situated almost against the wall. In
the back of the room a comparatively big cupboard is visible. Behind the bar
a norse small ugly dwarf is cleaning some glasses. On the bar you see a sign
on a piece of wood, apparently this is the menu for the day. Scattered among
the tables are groups of people, playing what seems to be a dwarfish version
of Poker.  You see a sign on the wall behind the counter.<P>
', north=0 where id=9;

update rooms set south=0 where id=20;

#reset chest thingy
update items set description='
<H1>The Lock</H1><HR> You look carefully at
the lock of the chest. It is very well made.
Somebody at least knows his business. You can\'t open it, that is for
sure.  Why don\'t you try finding the key? There is probably no other way
to open this chest but with the key.<P> ', adject1='rusty' where id=-91;

update rooms set contents='
<H1><IMG SRC=\"http://www.karchan.org/images/gif/hidden01.gif\"> The Hidden
Room</H1> <font size=+3> Y</font>ou are in the middle of a hidden room on
the upper floor of the Inn.  It is very dusty and all around sticky old
cobwebbs have been made by the usual little insects. On the far side of the
room a strong iron chest can be seen. Above you you can see a lot of wooden
stuff to hold up the roof. To the south there is a way out, down the
staircase that is visible there.<P>' where id=20;

END_OF_DATA

/karchan/mud/sql/mysql_talk "You hear a rumble, and before you realise \
what is happening, an avalanche of stones block the way south.<BR>" 4
/karchan/mud/sql/mysql_talk "You hear a rumble, and before you realise \
what is happening, an avalanche of stones block the way north.<BR>" 23
