#!/bin/sh

cd /karchan/mud/sql/crontab

. ./../mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# Dumping data for items into table 'tmp_itemtable'
#

insert into tmp_itemtable select * from respawningitemtable;

END_OF_DATA

