#!/bin/sh

cd /karchan/mud/sql/crontab

. ./../mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# Dumping data for bots into tmp_usertable;
#

insert into tmp_usertable select * from bottable;

END_OF_DATA

