#!/bin/sh

cd /karchan/mud/sql/crontab

. ./../mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# Changeem
#
update bantable set days = days - 1 
	where days>0;
delete from bantable where days=0;

END_OF_DATA

