#!/bin/sh

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# Dumping data for table 'items'
#

# Room 48
replace into items values
(-90,'meadow','green','furtile','calm',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Meadow</H1>
You are standing on a meadow, with big rocks on it. It seems to be a very
nice meadow. Lot\'s of grass and a few bushes here and there. You notice that
a moss is growing at the foot of the rocks.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-90,'','',1,48,'','');
replace into itemtable values (-90,'','',1,48,'','');

replace into items values
(-92,'moss','soft', 'green','moist',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Moss</H1>
You have noticed the moss at the foot of the rocks, which are standing on
the meadow. It is dark green, and very soft. You should be able to pluck it,
but what should you do with it?<P>
','',0,0,0,0);

replace into tmp_itemtable values (-92,'','',1,48,'','');
replace into itemtable values (-92,'','',1,48,'','');

replace into items values
(-93,'rocks','tall','pointed','hard',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Rocks</H1>
Ancient stones can be seen here, standing on the small meadow. They are
stood erect, and must have been set there a very long time ago. Some people
say it\'s magic, some people say a whole lot of people helped to get them
there, some say giants have put them there, but you are a sobered up kind of
guy and do not believe all that nonsense. In all probability they are just a
bunch of vikings from the north, frozen into stone by an Wizard as a
punishment for plundering and looting the city of Pendulis.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-93,'','',1,48,'','');
replace into itemtable values (-93,'','',1,48,'','');

# Room 56
replace into items values
(-94,'tower','rundown','stone','dilapadated',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Tower</H1>
The tower to the south of you is very high, a little run down and
dilapadated and you are not certain wether it will come crashing down if
you shout to it a little hard. It is made of solid rocks, very careless
bunked together. You wonder how long this thing has been standing there. It
guards the boundaries of the city.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-94,'','',1,56,'','');
replace into itemtable values (-94,'','',1,56,'','');

# Room 58
replace into items values
(-95,'church','old','Pendulis','big',
0,0,0,0,'','',0,0,0,0,0,0,'<H1><IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/phil2b.gif\">
The Church of Karchan</H1>
This is de church of the city of Pendulis. Here, people come to pray, to
marry and to be buried. In fact, lots of the most important things that
happen in a man (c.q. woman => emancipation) during his lifetime, happen in
there or find a sequel in there.<P>
This church is very nice, made of rocks, chiseled, nige statues at the front
doors and generally nice. The windows seem to be made of tinted glass
representing pictures.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-95,'','',1,58,'','');
replace into itemtable values (-95,'','',1,58,'','');

replace into items values
(-96,'hedge','low','green','leafy',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Hedge</H1>
The hedge to the south of you is green and full of leaves. It seems that you
cannot proceed in that particular direction. The hedge is so full, you
cannot proceed.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-96,'','',1,58,'','');
replace into itemtable values (-96,'','',1,58,'','');

# Room 63
replace into items values
(-97,'altar','big','marble','cold',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Big Marble Altar</H1>
In front of you, you see a big marble altar standing on a small elevation on
the ground. The sun from behind the window shines just in the middle of the
altar, as if the designer of this church meant it to be just like this. It
is very hard and very cold. On it are standing two big golden chandeliers. A
small golden plate with the holy bread and a cup with the wine of christ are
standing approximately in the middle.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-97,'','',1,63,'','');
replace into itemtable values (-97,'','',1,63,'','');

replace into items values
(-98,'chairs','wooden','confession','rickity',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Confession Chairs</H1>
These chairs are for the people who are burdened with heavy sins and want to
be relieved. The chairs are very worn, which indicates a lot of sin is
present in this land. Maybe you could so something about that. You do not
have to go to confession, however.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-98,'','',1,63,'','');
replace into itemtable values (-98,'','',1,63,'','');

replace into items values
(-99,'chandeliers','golden','big','two',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Chandeliers</H1>
The chandeliers are really big and of solid gold. The sun on them reflects
straight into your eyes and make you whince. One is standing on the left
side of the altar, the other on the opposite side. They are carrying long
candles which can be lit if necessary. But now, it doesn\'t seem
necessary.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-99,'','',1,63,'','');
replace into itemtable values (-99,'','',1,63,'','');

replace into items values
(-100,'plate','golden','small','dirty',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Golden Plate</H1>
The golden plate is covered with dry crumbs of bread. Apparently this is for
the people who come in here. The golden plate is comparatively small and is
doesn\'t look very impressive, yet it has a certain splendour about it, like
it likes the job is has been given.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-100,'','',1,63,'','');
replace into itemtable values (-100,'','',1,63,'','');

replace into items values
(-101,'cup','small', 'golden','wine-filled',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Cup</H1>
The golden cup contains a red alcoholic wine. It looks like it has been used
more than once. Apparently it is in harmony
with the bread-crumbs. People here can donate bread and wine to the gods in
favour of luck or happiness. <P>
','',0,0,0,0);

replace into tmp_itemtable values (-101,'','',1,63,'','');
replace into itemtable values (-101,'','',1,63,'','');

replace into items values
(-102,'wine','full', 'red','alcoholic',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Wine</H1>
The red wine is comparatively strong and is located in the wine-glass.
Apparently the food and wine make a good meal.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-102,'','',1,63,'','');
replace into itemtable values (-102,'','',1,63,'','');

replace into items values
(-103,'bread','crumbs', 'of','dry',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Bread</H1>
Dry crumbs of bread are lying on a small gold plate, you see before you in
the middle of the altar. They appear to be part of a meal in the favour of
the gods. You could eat them, ofcourse, but that would probably invoke the
anger of the gods, who will certainly strike you with their lightning and
evaporate you, which would be a very nasty thing to experience.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-103,'','',1,63,'','');
replace into itemtable values (-103,'','',1,63,'','');

# Room 64
replace into items values
(-104,'bread','all', 'kinds of','of',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Bread</H1>
A lot of different kinds of bread are heaped upon the counter. You should be
able to buy some of it. Just read the sign.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-104,'','',1,64,'','');
replace into itemtable values (-104,'','',1,64,'','');

replace into items values
(-105,'counter','dark', 'oak','wooden',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Counter</H1>
It is a wooden counter with a huge amount of different kinds of bread heaped
upon it.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-105,'','',1,64,'','');
replace into itemtable values (-105,'','',1,64,'','');

replace into items values
(-119,'sign','yellow', 'plastered','small',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Sign in the Bakery</H1>
This list contains everything that can be bought here.<P>
<I>
<TABLE>
<TR>
<TH>________________________________
<TH>________________________________
</TR><TR><TH>A Loaf<TH>5 copper coins
</TR><TR><TH>A Raisin Bread<TH>4 copper coins
</TR><TR><TH>A Sugar Cookie<TH>5 copper coins
</TR><TR><TH>An Apple Tart<TH>5 copper coins
</TR><TR><TH>A Blueberry Tart<TH>5 copper coins
</TR><TR><TH>Gingerbread<TH>2 copper coins
</TR><TR><TH>A dry biscuit (tea with biscuits)<TH>2 copper coins
</TR> 
</TABLE>
</I>  
You should be able to <B>buy</B> something from the list. The items that
have been marked are not available yet. Still looking for appropriate
pictures for the drinks that are marked.<P>
','<H1>The Sign in the Bakery</H1>
This list contains everything that can be bought here.<P>
<I>
<TABLE>
<TR>
<TH>________________________________
<TH>________________________________
</TR><TR><TH>A Loaf<TH>5 copper coins
</TR><TR><TH>A Raisin Bread<TH>4 copper coins
</TR><TR><TH>A Sugar Cookie<TH>5 copper coins
</TR><TR><TH>An Apple Tart<TH>5 copper coins
</TR><TR><TH>A Blueberry Tart<TH>5 copper coins
</TR><TR><TH>Gingerbread<TH>2 copper coins
</TR><TR><TH>A dry biscuit (tea with biscuits)<TH>2 copper coins
</TR> 
</TABLE>
</I>  
You should be able to <B>buy</B> something from the list. The items that
have been marked are not available yet. Still looking for appropriate
pictures for the drinks that are marked.<P>

',0,0,0,0);

replace into tmp_itemtable values (-119,'','',1,64,'','');
replace into itemtable values (-119,'','',1,64,'','');

# Room 65
replace into items values
(-106,'ledger','oak', 'tall','wooden',
0,0,0,0,'','',0,0,0,0,0,0,'<H1><IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/ledger.gif\">The
Ledger</H1>
The wooden ledger has a paper attached to it. You can read the paper sign.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-106,'','',1,65,'','');
replace into itemtable values (-106,'','',1,65,'','');

replace into items values
(-107,'sign','attached', 'paper','small',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Sign at the Moneychangers Offices</H1>   
Our bank provides you with a cheap way to relieve you of the burden of heavy
coins. For each transaction we ask only one (1) silver coin.<P>
This is an example of what you can do:<BR>
<DL>
<DT>change silver to gold
<DD>This would make you change all your silver coins into as much gold as
possible.
<DT>change 1 gold to copper
<DD> This would change 1 gold coin to copper coins, which means that you
would get 100 copper coins.
<DT>minimize coins
<DD>This changes all coins into the most valuable types possible.
</DL>
For the experienced players, here is the format:<P>
change [&lt;number&gt;] &lt;copper, silver, gold&gt; to &lt;copper, silver,
gold&gt;
<P>
','<H1>The Sign at the Moneychangers Offices</H1>   
Our bank provides you with a cheap way to relieve you of the burden of heavy
coins. For each transaction we ask only a 5% fee.<P>
This is an example of what you can do:<BR>
<DL>
<DT>change silver to gold
<DD>This would make you change all your silver coins into as much gold as
possible.
<DT>change 1 gold to copper
<DD> This would change 1 gold coin to copper coins, which means that you
would get 100 copper coins.
<DT>minimize coins
<DD>This changes all coins into the most valuable types possible.
</DL>
For the experienced players, here is the format:<P>
change [&lt;number&gt;] &lt;copper, silver, gold&gt; to &lt;copper, silver,
gold&gt;
<P>
',0,0,0,0);

replace into tmp_itemtable values (-107,'','',1,65,'','');
replace into itemtable values (-107,'','',1,65,'','');

# Room 69
replace into items values
(-108,'tents','wooden', 'strong','sturdy',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>Tents</H1>
The tents seem to be able to carry quite a lot of goods. They are made of
sturdy wooden tables, covered with some sort of cloth against rain. Behind
them, noisy merchants advertise their goods.<P>
The merchants around you all chatter at you and try to pull you inside their
shops and stands. They offer you all sorts of goods. You can barely get
away from it all.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-108,'','',1,69,'','');
replace into itemtable values (-108,'','',1,69,'','');

replace into items values
(-109,'road','stone', 'Pendulic','old',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Road</H1>
The road appears to be leading into the city, away from the marketplace.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-109,'','',1,69,'','');
replace into itemtable values (-109,'','',1,69,'','');

# Room 70
replace into tmp_itemtable values (-108,'','',1,70,'','');
replace into itemtable values (-108,'','',1,70,'','');
replace into tmp_itemtable values (-109,'','',1,70,'','');
replace into itemtable values (-109,'','',1,70,'','');

# Room 71
replace into tmp_itemtable values (-108,'','',1,71,'','');
replace into itemtable values (-108,'','',1,71,'','');
replace into tmp_itemtable values (-109,'','',1,71,'','');
replace into itemtable values (-109,'','',1,71,'','');

# Room 72
replace into tmp_itemtable values (-108,'','',1,72,'','');
replace into itemtable values (-108,'','',1,72,'','');
replace into tmp_itemtable values (-109,'','',1,72,'','');
replace into itemtable values (-109,'','',1,72,'','');

# Room 73
replace into items values
(-110, 'chairs','wooden', 'rickity','old',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>Tables and chairs</H1>
Around you you see tables and chairs for the customers to sit on. They seem
in not so healthy state and most customers prefer to stand at the bar.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-110,'','',1,73,'','');
replace into itemtable values (-110,'','',1,73,'','');

replace into items values
(-111, 'tables','wooden', 'rickity','old',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>Tables and chairs</H1>
Around you you see tables and chairs for the customers to sit on. They seem
in not so healthy state and most customers prefer to stand at the bar.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-111,'','',1,73,'','');
replace into itemtable values (-111,'','',1,73,'','');

replace into items values
(-112, 'counter','strong', 'iron','dented',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Counter</H1>
The strong iron counter seems very heavy. Behind it an evil looking person is
standing with his hands on his thighs. On the counter you can see a menu of
the objects you can get here.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-112,'','',1,73,'','');
replace into itemtable values (-112,'','',1,73,'','');

replace into items values
(-113, 'menu','badly', 'written','maltreated',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>Menu</H1>
There are no items on the menu just yet, but I\'ll program them. Don\'t you
worry.<P>','',0,0,0,0);

replace into tmp_itemtable values (-113,'','',1,73,'','');
replace into itemtable values (-113,'','',1,73,'','');

replace into items values
(-114, 'sign','dilapadated', 'soggy','disreputable',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Sign</H1>
There is a soggy dilapadated sign on the wall. With an effort, you can read
it. It says:<P>
<Center><I><B>
Please don\'t ask for credit,<BR>
as a punch in the mouth often offends.<BR></B>
</I></Center><P>
','<H1>The Sign</H1>
There is a soggy dilapadated sign on the wall. With an effort, you can read
it. It says:<P>
<Center><I><B>
Please don\'t ask for credit,<BR>
as a punch in the mouth often offends.<BR></B>
</I></Center><P>
',0,0,0,0);

replace into tmp_itemtable values (-114,'','',1,73,'','');
replace into itemtable values (-114,'','',1,73,'','');

replace into items values
(-115, 'picture','clear', 'small','hung',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Picture</H1>
To the south wall a picture is hanging. It has a wooden frame and looks
quite old and dirty, in fact in perfect harmony with the rest of the
room.<P>
You see a mediocre man, probably the Innkeeper, standing in a river, with a
fishingrod in his left hand, and a tiny fish which would fit in a fish bowl
in his right hand. You particularly notice the stupifying grin on his face.
This is probably the only fish he ever caught, which tells you a lot about
both him and that fish.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-115,'','',1,73,'','');
replace into itemtable values (-115,'','',1,73,'','');

# Room 74
replace into items values
(-116, 'stones','large', 'flat','awry',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>Large, Flat Stones</H1>
The street is made up out of a lot of large flat stones. They seem to be
coming from the mountains, being all awry and large and cornered. Yet in
some way they all seem to fit very nicely together. A lot of men must have
had some time putting them together like this. They seem very heavy and
after all these years, they must be as hard to move as the mountains
themselves.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-116,'','',1,74,'','');
replace into itemtable values (-116,'','',1,74,'','');

replace into items values
(-117, 'marketplace','rather', 'large','noisy',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Marketplace</H1>
You notice a marketplace in the distance, it seems to be very noisy and it
might be possible to buy and sell certain things there.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-117,'','',1,74,'','');
replace into itemtable values (-117,'','',1,74,'','');

# Room 75
replace into tmp_itemtable values (-116,'','',1,75,'','');
replace into itemtable values (-116,'','',1,75,'','');
replace into tmp_itemtable values (-117,'','',1,75,'','');
replace into itemtable values (-117,'','',1,75,'','');


# Room 76
replace into tmp_itemtable values (-116,'','',1,76,'','');
replace into itemtable values (-116,'','',1,76,'','');
replace into tmp_itemtable values (-117,'','',1,76,'','');
replace into itemtable values (-117,'','',1,76,'','');

replace into items values
(-118, 'inn','seedy', 'looking','noisy',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Inn</H1>
There is a seedy Inn towards the west. It seems very insecure, dirty, and
dangerous. You almost cannot wait to enter it. Above the door, leading to the 
insideof the Inn, a board is hanging.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-118,'','',1,76,'','');
replace into itemtable values (-118,'','',1,76,'','');

replace into items values
(-120, 'board','suspended', 'wooden','name',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Board</H1>
A board suspended from the wall is waving softly in the wind on strong,
rusty, and slightly noisy chains. It seems to have some damnible writing on
it. It is very wornout from all environmental influences. It seems to be
able to come down at any moment. Luckily it is fastened to the wall with
solid chains. It has a golden rim along side it, which is almost completely
worn away. And in the center there are dark letters, surrounded by dark
green paint.<P>
','<H1>The Board</H1>
The board had some damnable writing on it. You can just make it out what it
used to be:   
<P>
<Center><I>The DewDrop Inn</I></Center>
',0,0,0,0);

replace into tmp_itemtable values (-120,'','',1,76,'','');
replace into itemtable values (-120,'','',1,76,'','');

replace into items values
(-121, 'chains','slightly', 'noisy','rusty',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Chains</H1>
The chains are there to keep the board from falling down. They are rusty but
strong but they will in time ofcourse give way to the all powerful forces of
gravity. When this happens you\'d better not be standing there.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-121,'','',1,76,'','');
replace into itemtable values (-121,'','',1,76,'','');

# Room 77
# Room 78
replace into items values
(-122, 'table','small', 'central','oak',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Table</H1>
A wooden table is situated in the centre of the room. There is nothing  
present on the table and it seems normal and uninteresting enough.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-122,'','',1,78,'','');
replace into itemtable values (-122,'','',1,78,'','');

replace into items values
(-123, 'mirror','dirty', 'silver','ill-kept',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Mirror</H1>
A mirror is hanging on the wall next to the door. It looks a little dirty,
and ill kept. Below it a washbasin is visible. You can look at yourself in
the mirror.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-123,'','',1,78,'','');
replace into itemtable values (-123,'','',1,78,'','');

replace into items values
(-124, 'washbasin','white', 'water-filled', 'clean',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>The Washbasin</H1>
A washbasin is hanging on the wall next to the door. It contains water for
washing hands. Above it, a mirror is visible.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-124,'','',1,78,'','');
replace into itemtable values (-124,'','',1,78,'','');

# Room 79
replace into items values
(-125, 'shop','leather', 'goods','clothing',
0,0,0,0,'','',0,0,0,0,0,0,'<H1>Leather goods Shop</H1>
To the north a leather shop is visible. There you could buy anything for a
strong sturdy jacket, to a leather bag to keep things in. You can see a sign
plastered to the wall outside the shop.<P>
','',0,0,0,0);

replace into tmp_itemtable values (-125,'','',1,79,'','');
replace into itemtable values (-125,'','',1,79,'','');
replace into tmp_itemtable values (-116,'','',1,79,'','');
replace into itemtable values (-116,'','',1,79,'','');

# Room 80
replace into tmp_itemtable values (-116,'','',1,80,'','');
replace into itemtable values (-116,'','',1,80,'','');
# Room 81
replace into tmp_itemtable values (-116,'','',1,81,'','');
replace into itemtable values (-116,'','',1,81,'','');
# Room 82
replace into tmp_itemtable values (-116,'','',1,82,'','');
replace into itemtable values (-116,'','',1,82,'','');
# Room 83


END_OF_DATA

