#!/bin/sh

cd /karchan/mud/sql   

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# update logonmessage
#

UPDATE logonmessage set message="<B>Logonmessage</B>
<BR>
<IMG SRC=\"http://www.karchan.org/images/gif/letters/w.gif\"
ALT=\"W\" ALIGN=left>
elcome to the Land of Karchan MUD, a land filled with mystery 
and enchantment, where weapons, magic, intelligence, and common 
sense play key roles in the realm. Where love and war can be one 
and the same. Where elves coexist peacefully with the humans, and 
make war with the dwarves. Where the sun rises, and the moon falls. 
Where one can change into a hero with a single swipe of his 
sword.<P>

The current deputies are: 
Kass, Kel, Bladestorm, Blackfyre, Legolas, Silverblade<P>

I invented something called <I>polls</I>. It is a
bit complicated, but it will sort itself out. There are two commands:
<UL>
<LI>poll &lt;number&gt;
<LI>poll &lt;comments&gt;
</UL>
<HR><I>What happened to you when the mud went down?</I><P>
<FORM>   
<input
type=\"radio\" name=\"poll\" value=\"1\" onClick=\"doClick(1)\">Didn't
effect me much, not like I enjoy the game anyway
<BR><input type=\"radio\" name=\"poll\" value=\"2\"
onClick=\"doClick(2)\">Fellt a small twinge inside.
<BR><input type=\"radio\" name=\"poll\" value=\"3\"
onClick=\"doClick(3)\">I have lots of other muds I play, I simply switched.
<BR><input type=\"radio\" name=\"poll\" value=\"4\"
onClick=\"doClick(4)\">Shivers down my back, sweating, paleness. First
withdrawal symptoms.
<BR><input type=\"radio\" name=\"poll\" value=\"5\"
onClick=\"doClick(5)\">Cowered beneath the staircase, because the end
of the world could not be far behind.
<BR><input type=\"radio\" name=\"poll\" value=\"6\"
onClick=\"doClick(6)\">Dude, you suck!
<BR><input type=\"radio\" name=\"poll\" value=\"7\"
onClick=\"doClick(7)\">Forget this! When is the fighting finally
coming back?
<P>
</FORM>
<SCRIPT>
<!-- Begin to hide sript contents from old browsers.
function doClick(number)
{
// window.alert(number)
   document.CommandForm.command.value=\"poll \" + number

}
// End the hiding here. -->
</SCRIPT>
<HR>
Regards and have fun!<P>
<I>Karn (Ruler of Karchan, Keeper of the Key to the Room of Lost
Souls)</I><P>

<I>To contact a Deputy, report a bug, contact Karn, or use email, <A
HREF=\"http://www.karchan.org/karchan/help/faq.html#38\" TARGET=\"_blank\">click here</A>.</I>
<P>

<I>Please read <A
HREF=\"http://www.karchan.org/karchan/help/thelaw.html\" TARGET=\"_blank\"><FONT
COLOR=red>The LAW (the most important Rules and Regulations of the game)</FONT></A>.</I>
<P>

If you are new to this game, and need help, please type <B>help</B> for a
listing 
of the commands, and <B>help &lt;command&gt;</B> for help on a specific 
command or subject. <P>

" where id=0;

END_OF_DATA

