#!/bin/sh

cd /karchan/mud/sql   

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# Check for 
#
# +---------------------+
# | Tables_in_mud       |
# +---------------------+
# | CHA                 |
# | CON                 |
# | DEX                 |
# | INTL                |
# | STR                 |
# | WIS                 |
# | ability_scores      |
# | actclaimed          |
# | action              |
# | answers             |
# | attributes          |
# | bantable            |
# | boards              |
# | bogus_itemtable     |
# | bottable            |
# | characterinfo       |
# | claimed             |
# | commands            |
# | commclaimed         |
# | containeditems      |
# | depalias            |
# | events              |
# | eventsclaimed       |
# | family              |
# | familyvalues        |
# | guilds              |
# | help                |
# | items               |
# | itemtable           |
# | library             |
# | logonmessage        |
# | mailtable           |
# | methclaimed         |
# | methods             |
# | negativeitem        |
# | olditem             |
# | oldmail             |
# | olduser             |
# | poll_values         |
# | polls               |
# | positiveitem        |
# | private_info        |
# | respawningitemtable |
# | rooms               |
# | sillynamestable     |
# | skills              |
# | skilltable          |
# | tmp_attributes      |
# | tmp_itemtable       |
# | tmp_mailtable       |
# | tmp_usertable       |
# | tmp_usertable2      |
# | treasure            |
# | unbantable          |
# | usertable           |
# +---------------------+
# 55 rows in set (0.01 sec)
# 

# fix all the GODS in order to not have their items erased
insert into usertable select * from tmp_usertable where god=2;

select distinct concat("delete from family where name='",family.name,"';")
from family left join usertable on usertable.name = family.name
where usertable.name is  NULL;

select distinct concat("delete from itemtable where belongsto='",family.name,"';")
from family left join usertable on usertable.name = family.name
where usertable.name is  NULL;

select distinct concat("delete from itemtable where id=",itemtable.id,";")
from itemtable left join items on items.id = itemtable.id
where items.id is NULL;

select distinct concat("delete from tmp_itemtable where id=",tmp_itemtable.id,";")
from tmp_itemtable left join items on items.id = tmp_itemtable.id
where items.id is NULL;

select distinct concat("delete from itemtable where belongsto='",itemtable.belongsto,"';")
from itemtable left join usertable on usertable.name = itemtable.belongsto
where usertable.name is NULL;

select distinct concat("delete from tmp_itemtable where belongsto='",tmp_itemtable.belongsto,"';")
from tmp_itemtable left join usertable on usertable.name = tmp_itemtable.belongsto
where usertable.name is NULL;

END_OF_DATA

