#!/bin/sh

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# Dumping data for table 'items'
#

REPLACE INTO items VALUES (39,'0000001','special','special','special',
0,0,0,0,'','',1,0,0,0,0,0,'','',0,0,0,0);

END_OF_DATA

