#!/bin/sh

cd /karchan/mud/sql   

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# update logonmessage
#

update itemtable 
set race = 'human'
where race<>'human' and
race<>'fox' and
race<>'rabbit' and
race<>'duck' and
race<>'wolf' and
race<>'chipmunk' and
race<>'ropegnaw'
END_OF_DATA

