#!/bin/sh

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA

delete from tmp_itemtable where id=$1;
delete from itemtable where id=$1;
delete from items where id=$1;

END_OF_DATA

