#!/bin/sh

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Empty tables
#
#delete from items;
#delete from itemtable; 
#delete from tmp_itemtable;

#
# Dumping data for table 'items'
#

REPLACE INTO items VALUES (40,'corpse','dead','human','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>A Human Corpse</H1>
You examine the corpse carefully. It appears to be dead, and was
human.<P>','',0,0,0,0);

REPLACE INTO items VALUES (41,'corpse','dead','dwarf','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>A Dwarfish Corpse</H1>
You examine the corpse carefully. It appears to be dead, yet you can still
discern its dwarfish features.<P>','',0,0,0,0);

REPLACE INTO items VALUES (42,'corpse','dead','elf','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>An Elvish Corpse</H1>
You examine the corpse carefully. It appears to be dead, yet you can still
discern its slim elvish features.<P>','',0,0,0,0);

REPLACE INTO items VALUES (43,'corpse','dead','rabbit','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Rabbit</H1>
You examine the corpse carefully. It appears to be dead, yet you can still
discern its furry coat of white hair.<P>','',0,0,0,0);

REPLACE INTO items VALUES (44,'corpse','dead','duck','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Duck</H1>
You examine the corpse carefully. It appears to be of a dead duck, as you
can make out of its bill and the feathers.<P>','',0,0,0,0);

REPLACE INTO items VALUES (45,'corpse','dead','wolf','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Wolf</H1>
You examine the corpse carefully. It appears to be dead, yet you can still
discern its coat of grey-white streaked fur, and a set of sharp teeth.<P>','',0,0,0,0);

REPLACE INTO items VALUES (46,'corpse','dead','chipmunk','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Chipmunk</H1>
You examine the corpse carefully. It appears to be dead, yet you can still
discern its furry coat of light-brown hair.<P>','',0,0,0,0);

REPLACE INTO items VALUES (47,'corpse','dead','fox','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Fox</H1>
You examine the corpse carefully. It appears to be dead, yet you can still
discern its furry coat of red hair.<P>','',0,0,0,0);

REPLACE INTO items VALUES (48,'corpse','dead','ropegnaw','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Ropegnaw</H1>
You examine the corpse carefully. It appears to be dead, yet you can still
discern its disgusting little insect body.<P>','',0,0,0,0);

REPLACE INTO items VALUES (49,'corpse','dead','buggie','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Buggie</H1>
Bugs. You hate them. Good that this one at least seems to be dead.
<P>','',0,0,0,0);

REPLACE INTO items VALUES (50,'corpse','dead','ooze','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Ooze</H1>
You examine the corpse carefully. It appears to be dead, slimey, and blueish
with a little light emanating from it which seems to disappear rather
rapidly.<P>','',0,0,0,0);

REPLACE INTO items VALUES (51,'corpse','dead','troll','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Troll</H1>
You examine the corpse carefully. It appears to be dead, yet you can still
discern its ugly face, and shabby clothing.<P>','',0,0,0,0);

REPLACE INTO items VALUES (52,'corpse','dead','wyvern','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Wyvern</H1>
You examine the corpse of the bird carefully. It appears to be dead, yet you can still
discern its feathers and straight beak.<P>','',0,0,0,0);

REPLACE INTO items VALUES (54,'corpse','dead','zombie','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Zombie</H1>
You examine the leftovers of a zombie. It\'s very odd to have to examine a
corpse which was already a corpse, even when it was alive. A distinct smell
is emanating from it and you feel a suddenly reluctance to go on.<P>','',0,0,0,0);

REPLACE INTO items VALUES (54,'corpse','dead','sentry','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of a Sentry</H1>
This must be the corpse of one of the sentries in front of the Dark Castle.
It appears to be dead, but you don\'t feel like turning your back on it.
<P>','',0,0,0,0);

REPLACE INTO items VALUES (55,'remains','some','sad','disgusting',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>Some sad remains</H1>
Some sad remains are here, remains of what at one time must have been a
living breathing being. However, slowly you notice even these remains
decaying, slowly evolving back to the dust.<P>
','',0,0,0,0);

REPLACE INTO items VALUES (84,'corpse','dead','otter','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Otter</H1>
You are looking at the corpse of what once was a otter.<P>
','',0,0,0,0);

REPLACE INTO items VALUES (85,'corpse','dead','buck','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Buck</H1>
You are looking at the corpse of what once was a buck.<P>
','',0,0,0,0);

REPLACE INTO items VALUES (86,'corpse','dead','rat','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Rat</H1>
You are looking at the corpse of what once was a rat.<P>
','',0,0,0,0);

REPLACE INTO items VALUES (87,'corpse','dead','turtle','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Turtle</H1>
You are looking at the corpse of what once was a turtle.<P>
','',0,0,0,0);

REPLACE INTO items VALUES (88,'corpse','dead','tarantula','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Tarantula</H1>
You are looking at the corpse of what once was a tarantula.<P>
','',0,0,0,0);

REPLACE INTO items VALUES (89,'corpse','dead','crocodile','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Crocodile</H1>
You are looking at the corpse of what once was a crocodile.<P>
','',0,0,0,0);

REPLACE INTO items VALUES (90,'corpse','dead','beaver','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Beaver</H1>
You are looking at the corpse of what once was a beaver.<P>
','',0,0,0,0);

REPLACE INTO items VALUES (91,'corpse','dead','raven','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Raven</H1>
You are looking at the corpse of what once was a raven.<P>
','',0,0,0,0);

REPLACE INTO items VALUES (92,'corpse','dead','seagull','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Seagull</H1>
You are looking at the corpse of what once was a seagull.<P>
','',0,0,0,0);

REPLACE INTO items VALUES (93,'corpse','dead','dummy','killed',
0,0,0,0,'','',0,0,0,0,1,0,'<H1>The Corpse of an Dummy</H1>
You are looking at the corpse of what once was a dummy.<P>
','',0,0,0,0);


END_OF_DATA

