#!/bin/sh

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('rabbit','duh','','Rabbit',
'-','-','rabbit','male','write','pretty','furry',
'cute', 'cuddly', 'blue-eyed', 'none', 'none', 'none', 'none',
1,1,1,7,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',0,0,0,0,0,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#
insert into bottable values('duck','duh','','duck',
'-','-','duck','male','brown','none','feathered',
'young', 'small', 'funny', 'none', 'none', 'none', 'none',
0,0,0,44,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',0,0,0,0,0,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('wolf','duh','','wolf',
'-','-','wolf','female','white','young','rugged',
'dangerous', 'ferocious', 'dark-eyed', 'big-teethed', 'none', 'none', 'none',
1,1,1,104,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',2,2,2,2,2,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('chipmunk','duh','','chipmunk',
'-','-','chipmunk','male','big-teethed','veteran','furry',
'brown', 'quick', 'dark-eyed', 'none', 'none', 'none', 'none',
1,1,1,19,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',0,0,0,0,0,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('fox','duh','','fox',
'-','-','fox','male','young','brown-red','grinning',
'agile', 'none', 'none', 'none', 'none', 'none', 'none',
1,1,1,33,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',1,1,1,1,1,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('ropegnaw','duh','','ropegnaw',
'-','-','ropegnaw','female','young','wimpy','micro',
'stupid', 'nasty', 'little', 'none', 'none', 'none', 'none',
1,1,1,178,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',0,0,0,0,0,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('buggie','duh','','buggie',
'-','-','buggie','male','young','wimpy','disgusting',
'micro', 'stupid', 'little', 'none', 'none', 'none', 'none',
1,1,1,184,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',0,0,0,0,0,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('ooze','duh','','ooze',
'-','-','ooze','female','big','aggressive','dumb',
'light-emitting', 'none', 'none', 'none', 'none', 'none', 'none',
1,1,1,193,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',15,5,5,5,5,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('troll','duh','','troll',
'-','-','troll','male','ugly','dirty','crippled',
'smelly', 'ragged', 'black-eyed', 'none', 'none', 'none', 'none',
1,1,1,113,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',3,3,3,3,3,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('wyvern','duh','','wyvern',
'-','-','wyvern','female','evil','brown','feathery',
'evil', 'none', 'none', 'none', 'none', 'none', 'none',
1,1,1,256,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',5,5,5,5,5,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('zombie','duh','','zombie',
'-','-','zombie','male','brown','large','evil',
'dark', 'undead', 'none', 'none', 'none', 'none', 'none',
1,1,1,258,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',5,5,5,5,5,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);
END_OF_DATA

/usr/local/mysql/bin/mysql --password=`cat /karchan/mud/sql/password.sql` mud <<END_OF_DATA
#
# Dumping data for bots
#

insert into bottable values('sentry','duh','','sentry',
'-','-','sentry','male','white','corpse-like','undead',
'roaming', 'nasty', 'none', 'none', 'none', 'none', 'none',
1,1,1,258,'',118,0,'',0,0,1,0,0,0,0,0,0,0,0,3,'',5,5,5,5,5,5,5,5,5,0,0,5,5,118,
'','','','','','','','','','','','','','','','','',1,1,1);

END_OF_DATA

