#!/bin/sh

cd /karchan/mud/sql   

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# update logonmessage
#

UPDATE logonmessage set message="<B>Logonmessage</B>
<BR>
<IMG SRC=\"/images/gif/letters/w.gif\"
ALT=\"W\" ALIGN=left>
elcome to the Land of Karchan MUD, a land filled with mystery 
and enchantment, where weapons, magic, intelligence, and common 
sense play key roles in the realm. Where love and war can be one 
and the same. Where elves coexist peacefully with the humans, and 
make war with the dwarves. Where the sun rises, and the moon falls. 
Where one can change into a hero with a single swipe of his 
sword.<P>

The current deputies are: 
Kass, Desdamona, Crissy, Legolas<P>

<HR>
Monday, May 3, 23:59<p>
Am about to go on holiday to visit my brother in Italy. When I get back
I plan on installing the new Java version of the mud, wether it is 
finished or not. Some functionality will be missing.
I will return during the weekend of the 15th of May.
Better hang on for a rough ride.
<p><I>Karn</I>
<HR>
Wednesday, February 18, 10:22<p>
One of the partitions of the drive was full. It happened to be the partition
that is used for storing the user logs.
<p>Sorry about that. It was the reason communication was problematic.
Have taken steps to prevent it from ever happening again.
<p><I>Karn</I>
<HR>
Saturday, January 24, 17:10<p>
Well, my home internet account has been reactivated, so I can maintain
everything from home again.<p>
Made some stupid mistakes in the php scripts. Fixed it, and the who list and
everything works again.<p>
<I>Karn</I>
<HR>
Monday, January 19, 09:15<p>
Great! Just great! Well, here comes some of the crap I\'ve had to deal with:
<UL>
<LI>my home cable internet connection is gone (they have shut me off because
I was sending bad ips onto the network. I managed to trace the problem to a
bad netmask, but they still have to reconnect me. What is it for way of
working to
first shut a persons connection down, and provide information only when I
call. Sheesh, the calls alone are a disaster. Helpdesk reconnects me to the
Technical Support. Technical Support reconnects me to the Misuse Department.
Still isn\'t fixed, will have to call Tuesday.)
Thank god I have Internet at work. 
<LI>my hosting company had an issue with their UPS, causing a reboot of
several machines (not only mine). Seems to have been fixed and I restarted
the mud server.
<LI>I\'ll see what I can do about the who list.
</UL>
Oh, and by the by, thank you for all the emails mentioning that Karchan was
down. It shows that people are still playing the game.
<P>
<I>Karn</I>
<HR>
Tuesday, January 06, 21:46<p>
Well, I decided to clean the place up. The bantable has been reset so
everyone can join the game. However, it probably means that the bantable
will be filled again quite quick as well. I also did a cleanup of everyone
who has not been online for the past 90 days, that should clean the place a
little up.<p>I\'ll see about being a little more active regarding this place.
<p><I>Karn</I>
<HR>
Thursday, December 25, 16:25<p>
I wish everyone a happy christmas and a happy new year!!!
<p><I>Karn</I>
<HR>
Thursday, November 27, 22:45<p>
Well, I got the emailaccounts up and running again. 
(you know, <A HREF=\"mailto:deputy@karchan.org\">deputy@karchan.org</A>
 and all that stuff.) I cannot make any promises about answering emails
ofcourse.<P>Also added PHP support
to the Apache server. If this does not mean anything to you, well, let me
tell you it is damn cool stuff. I am redoing the whole cgi-script thingy in
php as it takes way too much time to maintain. Check out the who list on the
main page for an example.
<P>
<I>Karn</I>
<HR>
Thursday, November 13, 22:20<p>
Well, the initial problem was a little one. The disk partition was full.
After deleting some files I restarted the server and suddenly nothing
worked.
<P>
Well, I have no idea what is wrong, but after some god-awful hack I got
things working for now. I have to get this program redone in Java and rather
right now, before the whole thing comes crashing down. Anyone care to help?<P>
In how far would you people mind if I get a preliminary version done in Java
that works flawlessly, but most of the functionality will be gone? Or would
you rather have the current situation, a shitty server program that restarts
itself every 30 minutes but has items and whatnot.<P>
<I>Karn</I>
<HR>
<I>To contact a Deputy, report a bug, contact Karn, or use email, <A
HREF=\"/karchan/help/faq.html#38\" TARGET=\"_blank\">click here</A>.</I>
<P>

<I>Please read <A
HREF=\"/karchan/help/thelaw.html\" TARGET=\"_blank\"><FONT
COLOR=red>The LAW (the most important Rules and Regulations of the game)</FONT></A>.</I>
<P>

If you are new to this game, and need help, please type <B>help</B> for a
listing 
of the commands, and <B>help &lt;command&gt;</B> for help on a specific 
command or subject. <P>

" where id=0;

END_OF_DATA

