#!/bin/sh

cd /karchan/mud/sql   

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA

#
# Dumping data for table 'skills'
#

INSERT INTO skills VALUES (0,'bare-handed combat',0,100,0,'','',1,0,2);
INSERT INTO skills VALUES (1, 'pick', 0, 100, 0, '', '', 1, 0, 2);
INSERT INTO skills VALUES (2, 'knife', 0, 100, 0, '', '', 1, 0, 2);



END_OF_DATA

