#!/bin/sh

/usr/bin/mysql --password=pagedown mud <<END_OF_DATA

#
# Dumping data for table 'action'
#

# 0-4 : use pick with stones
replace into action values(0, '<H1>The Stones</H1><HR>
You take the pick into both your hands, and raise it far above your
head. With a thundering crash you let it come down hard on the stones. You
are splitting them all to pieces. It does take you some time. You
continually raise the pick above your head and let it come down again. So
many times, that is almost comes to be an automatism. But at last, you have
made the way clear of those stones and finally people can traverse it once
again.<P>');

replace into action values(1, '<H1>The Chain</H1><HR>
You take the chain into both your hands
and you give it a good yank! Something amazing happens. You pull the chain a   
few centimeters out of the wall. At the same moment behind the wall, if you
listen very well, you hear the cracking of wood, the squaking of rope and  
other ominous sounds. My god! What have you done! What devilish boobytrap   
will within a few moments crush you to atoms? You stand still unable to get
away from the fate that awaits you.<P> However, within a few minutes, the  
sounds stop and everything is back in its usual order. Nothing happened, but
what was that all about?<P>');

replace into action values(2, '<H1>The Jump</H1><HR> You jump into the lake
with a loud splash. The water
is very cold, but that doesn\'t really bother you. You swim under water and
you can see a glimpse of a tunnel going all the way to the east. You swim
into the tunnel.<P> After a while you start to get a breathing problem and 
you say to yourself:
&quot;If I don\'t get to some air some, I am going to die in this lonely
tunnel.&quot; You swim on, and suddenly you arrive at a gate of rusty iron.
There is no way in hell that you are going through that gate. You take it in
both your hands and rattle all you can, but the gate won\'t move an inch. Oh
boy! You are in trouble now. There is no way out. Slowly you run out of air.
With your hands clutched to the gate you die a slow and very painful
death.<Center><H1>The End</H1></Center><P> You are dead. You are at the
moment in a dark room. You can\'t see anything. You hear sighs.<P> A voice 
says (behind you): Oh no, not another one...<P> Another voice sighs : They 
just keep on comin\'.<P> Suddenly, in the distance, you see a light which
slowly comes closer. As it comes closer, you see that it is a lantern which 
is being held by somebody (or something you can\'t really make it out). That
someone is getting closer. When he is standing right before you, you have a
good view of who he is. You can\'t see his face, because that is hidden by a
cap. He is all in black.<P> You say: Hey, did somebody just die?<P> He is   
carrying a heavy axe with him. This, you gather, must be Mr. Death himself.
He swings back his axe, and you hide your hands behind your face. (That
shouldn\'t however help much) Than the axe comes crushing down.<P>(Type
<B>look around</B>)
');

replace into action values(3, '<H1>The Jump</H1><HR> You jump into the lake
with a loud splash. The water
is very cold, but that doesn\'t really bother you. You swim under water and 
you can see a glimpse of a tunnel going all the way to the east. You swim   
into the tunnel.<P> After a while you start to get a breathing problem and
you say to yourself:
&quot;If I don\'t get to some air some, I am going to die in this lonely
tunnel.&quot; You swim on, and suddenly above you you can see a gate of iron
which has been pulles up into the upper wall. You thank all your gods, if
that gate wasn\'t pulled up like that there would be no way back for you.<P>
You swim on, and just when you think you can\'t take any more, there you are,
on the shore of the lake, at the other end of the cave. Slowly you stand up
and take a few deep gulps of fresh air. All is well that ends well.<P>
');

replace into action values(4, '<H1>The Jump</H1><HR> You jump into the lake
with a loud splash. The water
is very cold, but that doesn\'t really bother you. You swim under water and
you can see a glimpse of a tunnel going all the way to the west. You swim
into the tunnel.<P> After a while you start to get a breathing problem and 
you say to yourself:
&quot;If I don\'t get to some air some, I am going to die in this lonely
tunnel.&quot; You swim on, and suddenly you arrive at a gate of rusty iron.
There is no way in hell that you are going through that gate. You take it in
both your hands and rattle all you can, but the gate won\'t move an inch. Oh
boy! You are in trouble now. There is no way out. Slowly you run out of air.
With your hands clutched to the gate you die a slow and very painful
death.<Center><H1>The End</H1></Center><P> You are dead. You are at the
moment in a dark room. You can\'t see anything. You hear sighs.<P> A voice 
says (behind you): Oh no, not another one...<P> Another voice sighs : They 
just keep on comin\'.<P> Suddenly, in the distance, you see a light which
slowly comes closer. As it comes closer, you see that it is a lantern which 
is being held by somebody (or something you can\'t really make it out). That
someone is getting closer. When he is standing right before you, you have a
good view of who he is. You can\'t see his face, because that is hidden by a
cap. He is all in black.<P> You say: Hey, did somebody just die?<P> He is   
carrying a heavy axe with him. This, you gather, must be Mr. Death himself.
He swings back his axe, and you hide your hands behind your face. (That
shouldn\'t however help much) Than the axe comes crushing down.<P>(Type
<B>look around</B>)
');

replace into action values(5, '<H1>The Jump</H1><HR> You jump into the lake
with a loud splash. The water
is very cold, but that doesn\'t really bother you. You swim under water and 
you can see a glimpse of a tunnel going all the way to the west. You swim   
into the tunnel.<P> After a while you start to get a breathing problem and
you say to yourself:
&quot;If I don\'t get to some air some, I am going to die in this lonely
tunnel.&quot; You swim on, and suddenly above you you can see a gate of iron
which has been pulles up into the upper wall. You thank all your gods, if
that gate wasn\'t pulled up like that there would be no way back for you.<P>
You swim on, and just when you think you can\'t take any more, there you are,
on the shore of the lake, at the other end of the cave. Slowly you stand up
and take a few deep gulps of fresh air. All is well that ends well.<P>
');

replace into action values(6, '<H1><IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/winkel2.gif\">
The Hatch</H1><HR>
<! 53>You look ascensly at the dwarf called Karcas, to see if he is looking
your way. Then, when you think he isn\'t looking, you try to walk around the
counter to reach the hatch.<BR>
Suddenly Karcas looks your way...<P>
Karcas says [to you]: Hey, you young whittersnapper! What are you doing
coming round to my side!<P>
Karcas shouts [to you] (and goes red in the face): This is a shop! Get it?
You stand in front of the counter, and I stand behind it. That is the  
natural order of things. Now don\'t let me see you trying to come up here
again! You hear?<P>
Embarassed, you whisper a few words of apology and you pull back to your
side of the counter. That was a tuff break. Looks like we have to wait until
that stupid old biddy is gone.<P>
');

replace into action values(7, '<H1>You open the hatch</H1><HR>
[<A HREF=\"http://www.il.ft.hse.nl/~maartenl/DenD/Anim/win.mpg\">MPEG</A>]<P>
<! 54>Apparently you walk around the counter. You take the ring which is
fastened to the woodwork in both your hands and you give it a good yank. It
is stuck. One more try, you yank your hart out. The thing doesn\'t budge.<P>
Now what? You think very hard and you decide to give it one more excellent
try. You pull extremely hard at the ring and suddenly the hatch opens itself   
with a squeeeky sound. Apparently there is now a way down. If you want to go
down the hatch, typ <B>go down</B>.<P>
');

replace into action values(8, '<H1>The Escape</H1><HR>
You look carefully through a split in the hatch. Slowly you open it.
You can see the old dwarf which calls himself Karcas looking round. Slowly
you open the lid some more without noise. You try to sneak past Karcas, and
you are making it!<P>
Then, at the moment that you think you are in safety, Karcas turns round and
looks you full in the eye! First his face expresses surprise.<P>
Then it suddenly turns to anger.<BR>
Karcas says : What were you doing down there! I\'ll teach you to mess with
me!<BR>
 Before you know what hit you, Karcas comes
towards you, grabs you in the neck, and sets you sailing out the door of the
shop.<P>
Your short and first flight through the air is going to be short as you
notice the ground of the Square with the well coming towards you rather
fast. You bump on the ground, hard, slide west, and manage to give yourself
a nasty crack on the head due to the stoney well that\'s in the way.<BR>
You slowly stand up and carefully examine the lower part of your body where
Karcas\' leatherly shoe hit it.<P>
');

replace into action values(9, '<H1>The Wall</H1><HR>
Slowly you wave your hand in front of the wall. Nothing happens. Then, as
you continue to look, you see that the wall is suddenly gone. No transition,
no opening, nothing. You walk through what used to be the wall.<P>
   
You don\'t turn around, but instinctively you feel that the wall behind you
is a normal wall again, keeping you safe from influences outside.<P>
   
You are now inside the very heart of the MIF. In front of you a blue stone
hovers in the air. There appear to be no exits here.
<P>
');

replace into action values(10, '<H1>The Wall</H1><HR>
Slowly you wave your hand in front of the wall. Nothing happens. Then, as
you continue to look, you see that the wall is suddenly gone. No transition,
no opening, nothing. You walk through what used to be the wall.<P>

You don\'t turn around, but instinctively you feel that the wall behind you
is a normal wall again, keeping you safe from influences outside.<P>

You are now outside the MIF, in the Visitors Lounge. To the north is the
exit out.
<P>
');

replace into action values(11, '<H1>The old man</H1><HR>
You take the stick you are carrying and you give it to the old dwarf,
who is sitting on the bench.<P>
Karaoke says [to you] : Thank you very much, I really needed a stick. Now I
can walk again. This stick looks sturdy and losid and strong, I can rely on
it for my balance and strength. Now you have given me such a great thing. I
want to reward you, but I don\'t have anything of value.<P>
Karaoke pauses for a few seconds...<P>
Karaoke recommences [to you] : Wait, I do have something, I don\'t know if it
will help you very much, but a long time ago, when I was still fit to walk.
I found, in the Inn, a metal blue key, with which I could do nothing, yet I
kept it with me for very long. Maybe you can use it. Hereby I give you this
key, for lack of something better.<P>
Karaoke gives you a key.<P>
You now have a key.<P>
<Center><IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/key.gif\"></Center><P>
');

replace into action values(12, '<H1><IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/kistkey.gif\">
The Chest</H1><HR>
[<A HREF=\"http://http://lok.il.fontys.nl/~karchan/pictures/mpeg/hid.mpg\">MPEG</A>]<P>
<! 34>You put the key in the lock of the chest. It seems to fit perfectly.
Slowly you turn the key in the lock. 
<BR><Center><IMG SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/
kistkey2.gif\">
<BR></Center>
It is not easy, because it is very old
and hasn\'t been oiled in a million years. But finally you manage it and the
lock is open. You open the lid of the chest.<P>');

replace into action values(13, '<H1>The Waterfall</H1>
Slowly you concentrate yourself. Then you do a perfect impression of the
bird call of the Jara Jara Bird. Nothing happens. Then, as
you continue to look, you see that waterfall slowly splits in two different
streams. You can see a cavern, located behind the waterfall. You get into
the water, making your clothing slightly wet and go through the gap in the
waterfall.
<P>

You don\'t turn around, but instinctively you feel that the waterfall behind
you
is normal again, keeping you safe from influences outside.<P>

You are now inside the introductory chamber of the Guild of Rangers. There
is an exit north, into the Main Room.
<P>');

replace into action values(14, '<H1>The Waterfall</H1>
Slowly you concentrate yourself. Then you do a perfect impression of the
bird call of the Jara Jara Bird. Nothing happens. Then, as
you continue to look, you see that waterfall slowly splits in two different
streams. You can see outside, where the waterfall continues into a small
river. You go through the gap in the waterfall.
<P>

You don\'t turn around, but instinctively you feel that the waterfall behind
you
is normal again, keeping you safe from influences outside.<P>

You are now back outside, into the real and unsafe world of Karchan.
<P>');


END_OF_DATA

