#!/bin/sh

cd /karchan/mud/sql   

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# update logonmessage
#

select concat("delete from tmp_itemtable where id=",id,";")
from items
where (adject1 like "%'%" or adject2 like "%'%" or adject3 like "%'%" or 
name like "%'%") and id>0;

select concat("delete from itemtable where id=",id,";")
from items
where (adject1 like "%'%" or adject2 like "%'%" or adject3 like "%'%" or 
name like "%'%") and id>0;

select concat("delete from items where id=",id,";")
from items
where (adject1 like "%'%" or adject2 like "%'%" or adject3 like "%'%" or 
name like "%'%") and id>0;

END_OF_DATA

