#!/bin/sh

/usr/bin/mysql --password=`cat /karchan2/mud/sql/password.sql` mud <<END_OF_DATA

update rooms set contents='<H1><IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/kamer.gif\">Karn and
Westril\'s
Room</H1> <IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/letters/y.gif\"
ALIGN=left>ou are
presently in the little living room, normally occupied by Karn and Westril.
Solid stone walls of the castle surround this small room, yet it is not
devoid of life\'s simple pleasures.
<P> In the corner
of the room, a long comfortable bed can be seen, available to visitors who
are unable to make the long journey back home. To the wall a door leads
south, and a chair and table are situated. Apart
from this the room looks sparce, almost ascetic.<P>
To the east, you can catch a glimpse of the bedroom.<P>
', east=235 where id=61;

update rooms set contents='<H1><IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/jpeg/hemelbed2.jpg\">The
Bedroom</H1> <IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/letters/t.gif\"
ALIGN=left>his is the bedroom of Westril and Karn, and you marvel at it\'s
simplicity of design, yet abundance of comfort.
<P>
You notice that the difference with the previous room is obvious, a lot more
style and taste. It must be that Westril herself had a hand in the
arrangings. You see a milky-white oak cupboard standing against the wall. In
the center of the room, almost dominating the room in fact, is a large bed,
matching the colour of the cupboard perfectly. It\'s predominatedly white and
seems very soft, enticing you to a slight nap.<P>
To the west is an exit leading into the small living room.<P>
', south=0, north=0, west=61, east=0, up=0, down=0 where id=235;

update rooms set contents='<H1><IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/winkel1.gif\">The
little Shop</H1> <IMG
SRC=\"http://lok.il.fontys.nl/~karchan/pictures/gif/letters/y.gif\"
ALIGN=left>ou are
standing in front of the counter of the little shop. Everywhere around you,
articles are spread out. You see bottles which have strange glowing fluids
in them, also has the shop a great collection of primitive weapons, either
to kill or to hurt vehemently. A list is plastered to the west wall. You can
read it from here.<P>


' where id=16;

END_OF_DATA

