#!/bin/sh

cd /karchan/mud/sql 

. ./mysql_constants

${MYSQL_BIN} -v -v -v -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA

check table action, answers, attributes,bantable,boards,bogus_itemtable,
bottable, characterinfo, commands,
containeditems,depalias,events,family,familyvalues,guilds,help,items,
itemtable, logonmessage,mailtable, methods, olditem, oldmail, olduser,
private_info,respawningitemtable, rooms, sillynamestable,
skills,skilltable,tmp_itemtable, tmp_mailtable, tmp_usertable,
tmp_usertable2, unbantable, usertable CHANGED;

END_OF_DATA