#!/bin/sh

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA

#
# Dumping data for table 'respawningitemtable'
#

UPDATE respawningitemtable SET amount=amount-1 where belongsto='Karcas' and
amount>10;
DELETE FROM respawningitemtable WHERE amount=0 and belongsto='Karcas';

INSERT INTO respawningitemtable VALUES (1,'','',1,5,'','');

END_OF_DATA

/usr/local/mysql/bin/mysql -p -s mud <<END_OF_DATA

INSERT INTO respawningitemtable VALUES (2,'','',1,20,'','');

END_OF_DATA

/usr/local/mysql/bin/mysql -p -s mud <<END_OF_DATA

INSERT INTO respawningitemtable VALUES (56,'tree','',1,12,'','');

END_OF_DATA

