#!/bin/sh

cd /karchan/mud/sql

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA

#
# Dumping data for table 'respawningitemtable'
#

select 'update usertable set race="',race,'" where name="',name,'"' from
usertable2;

END_OF_DATA

