#!/bin/sh

cd /karchan/mud/sql   

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA
#
# update logonmessage
#

UPDATE logonmessage set message='<B>Logonmessage</B>
<BR>
<IMG SRC=\"http://www.karchan.org/images/gif/letters/w.gif\"
ALT=\"W\" ALIGN=left>
elcome to the Land of Karchan MUD, a land filled with mystery 
and enchantment, where weapons, magic, intelligence, and common 
sense play key roles in the realm. Where love and war can be one 
and the same. Where elves coexist peacefully with the humans, and 
make war with the dwarves. Where the sun rises, and the moon falls. 
Where one can change into a hero with a single swipe of his 
sword.<P>

The current deputies are: 
Kass, Milady, Manatoba, Kel, Stanimir<P>

There is the possibility to add your personal data to the website!
It is called a <I>Character Sheet</I>. Fill one in or check out the other 
people that already have one. You can find it <A
HREF=\"http://www.karchan.org/cgi-bin/charactersheets.cgi\"
TARGET=\"_blank\">here</A>.<P>
Yep! The game is back online (sorta) and the operating system has been
updated. Still need to do some tweaking but 
it is workable again. Please email me if you notice that some things are 
still not working as they should.<P>
I hope this means the end of those database/harddisk errors we\'ve been
getting.<P>
Regards and have fun!<P>
<I>Karn (Ruler of Karchan, Keeper of the Key to the Room of Lost
Souls)</I><P>

<I>To contact a Deputy, report a bug, contact Karn, or use email, <A
HREF="http://www.karchan.org/karchan/help/faq.html#38" TARGET=\"_blank\">click here</A>.</I>
<P>

<I>Please read <A
HREF="http://www.karchan.org/karchan/help/thelaw.html" TARGET=\"_blank\"><FONT
COLOR=red>The LAW (the most important Rules and Regulations of the game)</FONT></A>.</I>
<P>

If you are new to this game, and need help, please type <B>help</B> for a
listing 
of the commands, and <B>help &lt;command&gt;</B> for help on a specific 
command or subject. <P>

' where id=0;

END_OF_DATA

