#!/bin/sh

cd /karchan/mud/sql   

. ./mysql_constants

${MYSQL_BIN} -h ${MYSQL_HOST} -u ${MYSQL_USR} --password=${MYSQL_PWD} -s ${MYSQL_DB} <<END_OF_DATA

delete from tmp_itemtable where id=$1;
delete from itemtable where id=$1;
delete from items where id=$1;

END_OF_DATA

