#!/bin/sh

/usr/local/mysql/bin/mysql -h www.karchan.org -u karn --password=`cat /karchan/mud/sql/password.sql` -s mud <<END_OF_DATA
#
# optimize all tables
#

OPTIMIZE TABLE CHA;
OPTIMIZE TABLE CON;
OPTIMIZE TABLE DEX;
OPTIMIZE TABLE INTL;
OPTIMIZE TABLE STR;
OPTIMIZE TABLE WIS;
OPTIMIZE TABLE ability_scores;
OPTIMIZE TABLE action;
OPTIMIZE TABLE answers;
OPTIMIZE TABLE bantable;
OPTIMIZE TABLE bogus_itemtable;
OPTIMIZE TABLE bottable;
OPTIMIZE TABLE bugreportlist;
OPTIMIZE TABLE claimed;
OPTIMIZE TABLE depalias;
OPTIMIZE TABLE help;
OPTIMIZE TABLE items;
OPTIMIZE TABLE itemtable;
OPTIMIZE TABLE logonmessage;
OPTIMIZE TABLE mailtable;
OPTIMIZE TABLE monster;
OPTIMIZE TABLE negativeitem;
OPTIMIZE TABLE objects;
OPTIMIZE TABLE olditem;
OPTIMIZE TABLE oldmail;
OPTIMIZE TABLE olduser;
OPTIMIZE TABLE positiveitem;
OPTIMIZE TABLE respawningitemtable;
OPTIMIZE TABLE rooms;
OPTIMIZE TABLE rooms2;
OPTIMIZE TABLE rooms3;
OPTIMIZE TABLE sillynamestable;
OPTIMIZE TABLE skills;
OPTIMIZE TABLE skilltable;
OPTIMIZE TABLE tmp_itemtable;
OPTIMIZE TABLE tmp_mailtable;
OPTIMIZE TABLE tmp_usertable;
OPTIMIZE TABLE todo;
OPTIMIZE TABLE treasure;
OPTIMIZE TABLE unbantable;
OPTIMIZE TABLE usertable;
OPTIMIZE TABLE usertable_corrupted;
OPTIMIZE TABLE weapons;

END_OF_DATA

